repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
  - hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
    repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v7.0.0
  - hooks:
      - id: credo-check
    repo: git@github.com:elephantoss/pre-commit-credo.git
    rev: v0.0.1
